#!/usr/bin/env bash

# Define the repository owner, name, and branch
owner="uday-sudo"
repo="wallpapers"
branch=$(git branch --show-current)

# Function to generate raw URL for a file
genRawUrl() {
  echo "https://raw.githubusercontent.com/${owner}/${repo}/${branch}/$1$2"
}

# Function to create collapsible sections
createSections() {
  echo ""
  for dir in $(ls -d */); do
	echo " "
    echo "## **${dir%/}**"
	echo " "
    for file in $(ls "$dir"); do
	  if [[ "$file" =~ \.(jpg|jpeg|png|gif|bmp|tiff|webp)$ ]]; then
		echo "<details>"
		echo "<summary>$file</summary>"
		echo "<br>"
		echo ""
		echo "![$file](/$dir$file)"
		echo ""
		echo "\`\`\`$(genRawUrl "$dir" "$file")\`\`\`"
		echo "</details>"
	  fi
    done
  done
}

main() {
  echo "# Wallpapers Repository"
  echo "<!-- This README.md file is generated automatically; any changes will be overridden -->"
  createSections
}

main > README.md

echo "README.md generated successfully!"